wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684302197.361035
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 2
      - 13
      - 23
      4: 3.10.11
      5: 0.15.2
      6: 4.29.2
      8:
      - 1
      - 5
      - 12
